sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
before_script:
    - npm install hexo-generator-searchdb --save
    - npm uninstall hexo-generator-index --save
    - npm install hexo-generator-index-pin-top --save
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public


notifications:
   email:
     recipients:
       - hanerzamora@gmail.com
         #-
     on_success: never # default: change
     #on_success: change # default: change
     on_failure: always # default: always
